### PR TITLE
Add Malay stop words list

### PR DESCRIPTION
**Pull request by jawsvk**
Add stop words for the malay language

### CODE REVIEW

**Comment by ddhira123** [comment]
Please repair your stop words list according to the rules @jawsvk

**Comment by jawsvk** [comment]
> Please repair your stop words list according to the rules @jawsvk

I'm sorry, but do you mind giving me a hint on what to repair? 
From what I can see, the words are as required, in lowercase, and one word per line, and there are at least 10 lines in the file. After creating the file, I ran `parser.py` but there were no changes

**Comment by ddhira123** [comment]
@jawsvk For example, `acap kali` is two words in one line. I have repaired the checker.py script so you can see the error when commiting. Please pull the changes from the main repo to your forked repo. Thank you

**Comment by jawsvk** [comment]
> @jawsvk For example, `acap kali` is two words in one line. I have repaired the checker.py script so you can see the error when commiting. Please pull the changes from the main repo to your forked repo. Thank you

Thanks @ddhira123 , I cleaned up the list already. It should be okay now

**Pull request merged**
